version: '3.8'

services:
  main:
    container_name: main
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:15.1
    networks:
      - webnet
    environment:
      - POSTGRES_DB: ${DB_NAME}
      - POSTGRES_USER: ${DB_USERNAME}
      - POSTGRES_PASSWORD: ${DB_PASSWORD}
      - PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - /var/lib/postgresl/data
networks:
  webnet:
volumes:
  pgdata: